trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: tfVars

stages:
  - stage: Infracost
    jobs:
    - job: Analysis
      steps:
      - task: InfracostSetup@1
        displayName: 'Infracost : Install'
        inputs:
          apiKey: '$(infracost)'
          version: '0.10.x'
          currency: 'EUR'

      - task: Bash@3
        displayName: 'Infracost : Analysis'
        inputs:
          targetType: 'inline'
          script: |
            infracost breakdown --path .